name: EC2 Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v2
      - name: Stop PM2
        uses: alinz/ssh-scp-action@master
        with:
          port: 22
          key: ${{ secrets.EC2_KEY }}
          host: ${{ secrets.EC2_HOST }}
          user: ${{ secrets.EC2_USER }}
          ssh_before: |
            pm2 kill
      - name: Copy Files
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          remote_path: /var/www/ipaasincendin/
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USER }}
          remote_key: ${{ secrets.EC2_KEY }}
      - name: Start PM2
        uses: alinz/ssh-scp-action@master
        with:
          port: 22
          key: ${{ secrets.EC2_KEY }}
          host: ${{ secrets.EC2_HOST }}
          user: ${{ secrets.EC2_USER }}
          ssh_before: |
            cd /var/www/ipaasincendin
            sudo npm install
            cd /var/www/ipaasincendin/src
            export ENV=prod
            pm2 start index.js
