name: EC2 Deploy

on:
  push:
    branches: [ local ]

jobs:
  build:
    name: Lambda Deploy
    strategy:
      matrix:
        node-version: ['14']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Prepare application
        run: npm install && zip -r -q -1 ./bundle.zip .
      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ipaas-api-local
          zip_file: bundle.zip
