name: EC2 Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Lambda Deploy
      strategy:
        matrix:
          node-version: [14.x]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout files
          uses: actions/checkout@v2
        - name: Use Node ${{ matrix.node-version }}
          uses: actions/setup-node@v1.4.2
          with:
            node-version: ${{ matrix.node-version }}
        - name: Build application
          run: npm install && npm run build && zip -qq -r -j ./bundle.zip ./dist/*
        - name: Deploy to AWS Lambda
          uses: appleboy/lambda-action@master
          with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_region: ${{ secrets.AWS_REGION }}
            function_name: ipaas-api-prod
            zip_file: bundle.zip
            